version: '3.4'

services:
  aggrid1:
    image: aggrid1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3002"
    networks:
      - aggrid-network1

  aggrid-nginx1:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key:ro
      - ./ssl/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt:ro
      - ./ssl/dhparam.pem:/etc/nginx/dhparam.pem:ro
    depends_on:
      - aggrid1
    ports:
      - "8080:80"
      - "8443:443"  
    networks:
      - aggrid-network1

networks:
  aggrid-network1:
